"""generated test models

Revision ID: 06f00ec58290
Revises: 5390fa1fb1b5
Create Date: 2026-07-16 14:43:15.680346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f00ec58290'
down_revision = '5390fa1fb1b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_test',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_template_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'closed')", name='ck_generated_test_status'),
    sa.ForeignKeyConstraint(['test_template_id'], ['test_template.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_test_test_template_id'), ['test_template_id'], unique=False)

    op.create_table('generated_test_question',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('generated_test_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('display_position', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('display_position >= 1', name='ck_generated_test_question_position'),
    sa.ForeignKeyConstraint(['generated_test_id'], ['generated_test.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_test_id', 'display_position', name='uq_generated_test_question_position'),
    sa.UniqueConstraint('generated_test_id', 'question_id', name='uq_generated_test_question_question')
    )
    with op.batch_alter_table('generated_test_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_test_question_generated_test_id'), ['generated_test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_test_question_question_id'), ['question_id'], unique=False)

    op.create_table('generated_test_answer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('generated_test_question_id', sa.BigInteger(), nullable=False),
    sa.Column('answer_option_id', sa.BigInteger(), nullable=False),
    sa.Column('display_position', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('display_position BETWEEN 1 AND 5', name='ck_generated_test_answer_position'),
    sa.ForeignKeyConstraint(['answer_option_id'], ['answer_option.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_test_question_id'], ['generated_test_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_test_question_id', 'answer_option_id', name='uq_generated_test_answer_option'),
    sa.UniqueConstraint('generated_test_question_id', 'display_position', name='uq_generated_test_answer_position')
    )
    with op.batch_alter_table('generated_test_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_test_answer_answer_option_id'), ['answer_option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_test_answer_generated_test_question_id'), ['generated_test_question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_test_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_test_answer_generated_test_question_id'))
        batch_op.drop_index(batch_op.f('ix_generated_test_answer_answer_option_id'))

    op.drop_table('generated_test_answer')
    with op.batch_alter_table('generated_test_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_test_question_question_id'))
        batch_op.drop_index(batch_op.f('ix_generated_test_question_generated_test_id'))

    op.drop_table('generated_test_question')
    with op.batch_alter_table('generated_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_test_test_template_id'))

    op.drop_table('generated_test')
    # ### end Alembic commands ###
