"""question and answer models

Revision ID: 2040b0ada716
Revises: 28fee37d3d78
Create Date: 2026-07-16 08:18:03.191850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2040b0ada716'
down_revision = '28fee37d3d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_year_id', sa.Integer(), nullable=False),
    sa.Column('original_position', sa.SmallInteger(), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 25', name='ck_question_difficulty'),
    sa.CheckConstraint('original_position BETWEEN 1 AND 25', name='ck_question_original_position'),
    sa.ForeignKeyConstraint(['source_year_id'], ['source_year.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_source_year_id'), ['source_year_id'], unique=False)

    op.create_table('answer_option',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('original_position', sa.SmallInteger(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.CheckConstraint('answer_text IS NOT NULL OR image_path IS NOT NULL', name='ck_answer_option_has_content'),
    sa.CheckConstraint('original_position BETWEEN 1 AND 5', name='ck_answer_option_position'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'original_position', name='uq_answer_option_question_position')
    )
    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_option_question_id'), ['question_id'], unique=False)

    op.create_table('question_grade',
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'grade_id')
    )
    op.create_table('question_topic',
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_topic')
    op.drop_table('question_grade')
    with op.batch_alter_table('answer_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_option_question_id'))

    op.drop_table('answer_option')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_source_year_id'))

    op.drop_table('question')
    # ### end Alembic commands ###
