"""source year table

Revision ID: 28fee37d3d78
Revises: 5c60f7916f1a
Create Date: 2026-07-16 07:59:00.911397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28fee37d3d78'
down_revision = '5c60f7916f1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_year',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_year')
    # ### end Alembic commands ###
