"""Add preferred language to competitors

Revision ID: 4143cd27578e
Revises: a9d936b9abd6
Create Date: 2026-09-03 11:44:53.947762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4143cd27578e'
down_revision = 'a9d936b9abd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=5), server_default='hu', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitor', schema=None) as batch_op:
        batch_op.drop_column('preferred_language')

    # ### end Alembic commands ###
