"""test template grade and topic relations

Revision ID: 5390fa1fb1b5
Revises: ced720db3f69
Create Date: 2026-07-16 13:31:38.955952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5390fa1fb1b5'
down_revision = 'ced720db3f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_template_grade',
    sa.Column('test_template_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_template_id'], ['test_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_template_id', 'grade_id')
    )
    op.create_table('test_template_topic',
    sa.Column('test_template_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_template_id'], ['test_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_template_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_template_topic')
    op.drop_table('test_template_grade')
    # ### end Alembic commands ###
