"""add manual test template questions

Revision ID: 5eed06b976ba
Revises: 717acc879328
Create Date: 2026-09-09 08:13:05.029691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eed06b976ba'
down_revision = '717acc879328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_template_question',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('test_template_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.BigInteger(), nullable=False),
    sa.Column('display_position', sa.SmallInteger(), nullable=False),
    sa.CheckConstraint('display_position >= 1', name='ck_test_template_question_position'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_template_id'], ['test_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_template_id', 'display_position', name='uq_test_template_question_position'),
    sa.UniqueConstraint('test_template_id', 'question_id', name='uq_test_template_question_question')
    )
    with op.batch_alter_table('test_template_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_template_question_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_template_question_test_template_id'), ['test_template_id'], unique=False)

    with op.batch_alter_table(
        'test_template',
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                'selection_mode',
                sa.String(length=20),
                server_default='automatic',
                nullable=False,
            )
        )
        batch_op.create_check_constraint(
            'ck_test_template_selection_mode',
            "selection_mode IN ('automatic', 'manual')",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'test_template',
        schema=None,
    ) as batch_op:
        batch_op.drop_constraint(
            'ck_test_template_selection_mode',
            type_='check',
        )
        batch_op.drop_column('selection_mode')

    with op.batch_alter_table('test_template_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_template_question_test_template_id'))
        batch_op.drop_index(batch_op.f('ix_test_template_question_question_id'))

    op.drop_table('test_template_question')
    # ### end Alembic commands ###
