"""add competitor attempts and answers

Revision ID: a0f3fc4a46ce
Revises: e5c468f99d88
Create Date: 2026-07-17 09:48:55.045832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f3fc4a46ce'
down_revision = 'e5c468f99d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_attempt',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('competitor_id', sa.BigInteger(), nullable=False),
    sa.Column('generated_test_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'submitted')", name='ck_competitor_attempt_status'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_test_id'], ['generated_test.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competitor_id', 'generated_test_id', name='uq_competitor_attempt_test')
    )
    with op.batch_alter_table('competitor_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_attempt_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_attempt_generated_test_id'), ['generated_test_id'], unique=False)

    op.create_table('competitor_answer',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_id', sa.BigInteger(), nullable=False),
    sa.Column('generated_test_question_id', sa.BigInteger(), nullable=False),
    sa.Column('generated_test_answer_id', sa.BigInteger(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['competitor_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generated_test_answer_id'], ['generated_test_answer.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_test_question_id'], ['generated_test_question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'generated_test_question_id', name='uq_competitor_answer_question')
    )
    with op.batch_alter_table('competitor_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_answer_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_answer_generated_test_answer_id'), ['generated_test_answer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_answer_generated_test_question_id'), ['generated_test_question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitor_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_answer_generated_test_question_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_answer_generated_test_answer_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_answer_attempt_id'))

    op.drop_table('competitor_answer')
    with op.batch_alter_table('competitor_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_attempt_generated_test_id'))
        batch_op.drop_index(batch_op.f('ix_competitor_attempt_competitor_id'))

    op.drop_table('competitor_attempt')
    # ### end Alembic commands ###
