"""add competitor admin flag

Revision ID: a9d936b9abd6
Revises: a0f3fc4a46ce
Create Date: 2026-07-17 11:10:09.496058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d936b9abd6'
down_revision = 'a0f3fc4a46ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitor', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
