"""Versenyzo tabla letrehozasa

Revision ID: e5c468f99d88
Revises: 06f00ec58290
Create Date: 2026-07-17 07:56:18.059698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c468f99d88'
down_revision = '06f00ec58290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitor_grade_id'), ['grade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_competitor_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitor_username'))
        batch_op.drop_index(batch_op.f('ix_competitor_grade_id'))

    op.drop_table('competitor')
    # ### end Alembic commands ###
